### ISSUE TITLE
Improve `visit()` decorator's argument syntax

### ISSUE THREAD

**Issue by cabiad** [tophat/codewatch#15]
See https://github.com/tophat/codewatch/pull/1#discussion_r233899075

> It's not clear to me what the normalization here (adding an initial cap to the passed in string param) adds to our API.
> 
> Maybe `node_name` should have to be a valid node class name?
> 
> I might also consider making the param to `visit` the actual class, but the boilerplate of importing everything you need seems painful. Would give us the comfy feeling of an enumeration though.

**Comment by cabiad** [comment]
See also https://github.com/tophat/codewatch/pull/1#discussion_r233900393

> Making this capable of taking either a single node or a list of nodes could be helpful. Might make the eventual implementation of helpers (say, a helper that can easily handle either Import or ImportFrom nodes) cleaner too

**Comment by lime-green** [comment]
Addressed by https://github.com/tophat/codewatch/pull/22
