### ISSUE TITLE
directory_filter should receive full relative path

### ISSUE THREAD

**Issue by lime-green** [tophat/codewatch#77]
Directory filter methods receive the folder name but should receive the full path, relative to the base directory

**Comment by noahnu** [comment]
@lime-green Changing the path supplied to the filter would be a breaking change.

Do we want to pass the dir path as a second argument to the filter function to preserve old behaviour, or just make the breaking change with the idea that the old behaviour is an unwanted "bug"? (Personally, I don't see the value of the current behaviour which doesn't include the full relative path. If anything it's misleading.)

**Comment by lime-green** [comment]
Yeah I think it’s better to resolve this as a breaking change, because like you said, it’s a troublesome bug

**Comment by noahnu** [comment]
Have a PR up to address this. Should this only apply to directory_filter, or file_filter as well? or perhaps file_filter should have a second parameter for directory?

**Comment by noahnu** [comment]
Fixed in #94
